import { useMemo } from 'react';
import { Grid3X3, AlertTriangle, TrendingUp, Download } from 'lucide-react';
import { TOPICS, MOOD_CONFIG } from '../data/topics';

// Map emotion to confusion intensity (0-1)
function confusionScore(emotion) {
  const scores = { CONFUSED: 1, STRESSED: 0.8, BORED: 0.4, CONFIDENT: 0.05 };
  return scores[emotion] || 0;
}

// Get cell color based on confusion score
function getCellColor(score) {
  if (score >= 0.8) return { bg: '#ef444466', border: '#ef4444', label: 'High Struggle' };
  if (score >= 0.5) return { bg: '#f59e0b44', border: '#f59e0b', label: 'Moderate' };
  if (score >= 0.2) return { bg: '#6366f133', border: '#6366f1', label: 'Slight' };
  return { bg: '#22c55e15', border: '#22c55e33', label: 'Clear' };
}

export default function ConfusionHeatmap({ emotionHistory, allStudentData }) {
  // Build heatmap data from emotion history
  const heatmapData = useMemo(() => {
    if (!emotionHistory || emotionHistory.length === 0) return null;

    // Group by topic
    const topicMap = {};
    emotionHistory.forEach(entry => {
      const key = entry.topic || 'Unknown';
      if (!topicMap[key]) topicMap[key] = [];
      topicMap[key].push(entry);
    });

    // Generate heatmap rows
    const rows = TOPICS.map(topic => {
      const entries = topicMap[topic.title] || [];
      const emotions = entries.map(e => e.emotion);
      const avgConfusion = emotions.length > 0
        ? emotions.reduce((sum, e) => sum + confusionScore(e), 0) / emotions.length
        : -1; // -1 = not attempted
      const avgTime = entries.length > 0
        ? entries.reduce((s, e) => s + (e.time || 0), 0) / entries.length / 1000
        : 0;
      const dominantEmotion = emotions.length > 0
        ? emotions.sort((a, b) =>
            emotions.filter(v => v === b).length - emotions.filter(v => v === a).length
          )[0]
        : null;

      return {
        topic: topic.title,
        shortTitle: topic.title.replace('What is ', '').replace('?', '').replace(' (Git)', ''),
        confusion: avgConfusion,
        avgTime: Math.round(avgTime),
        attempts: entries.length,
        dominantEmotion,
        keywords: topic.keywords.slice(0, 3),
      };
    });

    return rows;
  }, [emotionHistory]);

  // Overall insights
  const insights = useMemo(() => {
    if (!heatmapData) return [];
    const attempted = heatmapData.filter(r => r.confusion >= 0);
    if (attempted.length === 0) return [];

    const hardest = [...attempted].sort((a, b) => b.confusion - a.confusion)[0];
    const easiest = [...attempted].sort((a, b) => a.confusion - b.confusion)[0];
    const slowest = [...attempted].sort((a, b) => b.avgTime - a.avgTime)[0];

    const res = [];
    if (hardest && hardest.confusion >= 0.5) {
      res.push({ type: 'warning', text: `"${hardest.shortTitle}" caused the most confusion — needs re-teaching with simpler examples.` });
    }
    if (easiest && easiest.confusion < 0.2) {
      res.push({ type: 'success', text: `"${easiest.shortTitle}" was clearly understood — student can move to advanced topics.` });
    }
    if (slowest && slowest.avgTime > 60) {
      res.push({ type: 'info', text: `"${slowest.shortTitle}" took ${slowest.avgTime}s avg — consider breaking into smaller chunks.` });
    }
    return res;
  }, [heatmapData]);

  const handleExport = () => {
    if (!heatmapData) return;
    const text = `HUNTER Confusion Heatmap Report\n${'='.repeat(40)}\n\n` +
      heatmapData.filter(r => r.confusion >= 0).map(r =>
        `${r.topic}\n  Confusion: ${Math.round(r.confusion * 100)}% | Time: ${r.avgTime}s | Emotion: ${r.dominantEmotion}`
      ).join('\n\n') +
      `\n\n--- Insights ---\n` +
      insights.map(i => `• ${i.text}`).join('\n') +
      `\n\nGenerated by HUNTER AI`;

    if (navigator.share) {
      navigator.share({ title: 'Confusion Heatmap', text });
    } else {
      navigator.clipboard.writeText(text);
    }
  };

  if (!heatmapData || heatmapData.filter(r => r.confusion >= 0).length === 0) {
    return (
      <div className="glass-card p-6 text-center">
        <Grid3X3 size={32} className="mx-auto mb-3 text-hunter-text-muted opacity-40" />
        <p className="text-sm text-hunter-text-muted">Complete topics to build the confusion heatmap</p>
        <p className="text-xs text-hunter-text-muted mt-1">Educators can see exactly where students struggle</p>
      </div>
    );
  }

  return (
    <div className="animate-fade-in-up space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Grid3X3 size={16} className="text-hunter-accent-light" />
          <h3 className="text-sm font-bold">Confusion Heatmap</h3>
        </div>
        <button onClick={handleExport} className="flex items-center gap-1 text-xs text-hunter-accent-light">
          <Download size={12} /> Export
        </button>
      </div>

      {/* Heatmap Grid */}
      <div className="space-y-2">
        {heatmapData.map((row, i) => {
          if (row.confusion < 0) {
            return (
              <div key={i} className="heatmap-row heatmap-row-empty">
                <div className="heatmap-label">{row.shortTitle}</div>
                <div className="heatmap-cell-empty">Not attempted</div>
              </div>
            );
          }
          const cell = getCellColor(row.confusion);
          return (
            <div key={i} className="heatmap-row" style={{ '--cell-bg': cell.bg, '--cell-border': cell.border }}>
              <div className="heatmap-label">{row.shortTitle}</div>
              <div className="heatmap-bar-container">
                <div className="heatmap-bar" style={{ width: `${Math.max(8, row.confusion * 100)}%`, background: cell.bg, borderColor: cell.border }}>
                  <span className="heatmap-bar-value">{Math.round(row.confusion * 100)}%</span>
                </div>
              </div>
              <div className="heatmap-meta">
                <span className="text-[10px]">{MOOD_CONFIG[row.dominantEmotion]?.emoji}</span>
                <span className="text-[10px] text-hunter-text-muted">{row.avgTime}s</span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Legend */}
      <div className="flex justify-center gap-3 mt-2">
        {[
          { label: 'Clear', color: '#22c55e' },
          { label: 'Slight', color: '#6366f1' },
          { label: 'Moderate', color: '#f59e0b' },
          { label: 'High', color: '#ef4444' },
        ].map(l => (
          <div key={l.label} className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-sm" style={{ background: l.color + '66' }} />
            <span className="text-[9px] text-hunter-text-muted">{l.label}</span>
          </div>
        ))}
      </div>

      {/* AI Insights */}
      {insights.length > 0 && (
        <div className="glass-card p-3 space-y-2">
          <div className="flex items-center gap-1.5 mb-1">
            <TrendingUp size={14} className="text-hunter-accent-light" />
            <span className="text-xs font-bold">Educator Insights</span>
          </div>
          {insights.map((insight, i) => (
            <div key={i} className={`heatmap-insight heatmap-insight-${insight.type}`}>
              {insight.type === 'warning' && <AlertTriangle size={12} />}
              <p className="text-xs">{insight.text}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
