import { useState } from 'react';
import { Lightbulb, Rocket, Sparkles, Clock, ArrowRight, Copy, RefreshCw } from 'lucide-react';
import { DREAM_PROJECT_SEEDS } from '../data/jobsData';

export default function DreamProjectGenerator({ studentName }) {
  const [interest, setInterest] = useState('');
  const [phase, setPhase] = useState('input'); // input | generating | result
  const [project, setProject] = useState(null);
  const [copied, setCopied] = useState(false);

  const generate = async () => {
    if (!interest.trim()) return;
    setPhase('generating');

    // Find matching seed
    const lower = interest.toLowerCase();
    const seed = DREAM_PROJECT_SEEDS.find(s =>
      lower.includes(s.keyword) || s.industry.toLowerCase().includes(lower)
    );

    // Try Claude API for personalized project
    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': window.__CLAUDE_API_KEY || '',
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true',
        },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 500,
          messages: [{
            role: 'user',
            content: `A student named ${studentName} from Tamil Nadu, India says: "${interest}"

Generate a personalized AI/tech project brief. Respond in this exact JSON format:
{
  "title": "Project title (creative, memorable)",
  "tagline": "One-line pitch (under 15 words)",
  "problem": "The real-world problem this solves (2 sentences, reference local Tamil Nadu context)",
  "solution": "What the student will build (2 sentences)",
  "techStack": ["3-4 technologies/tools needed"],
  "steps": ["Step 1 description", "Step 2", "Step 3", "Step 4"],
  "timeline": "Estimated time to build",
  "industry": "Industry sector",
  "district": "Most relevant Tamil Nadu district",
  "impact": "Who benefits and how (1 sentence)"
}

Make it specific to Tamil Nadu industries and contexts. If they mention textiles, think Tirupur/Coimbatore. Agriculture means Thanjavur/Erode. Health means Vellore/Chennai. Be creative and practical.`
          }],
        }),
      });

      if (res.ok) {
        const data = await res.json();
        const text = data.content?.[0]?.text || '';
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          setProject(JSON.parse(jsonMatch[0]));
          setPhase('result');
          return;
        }
      }
      throw new Error('fallback');
    } catch {
      // Fallback using seed data
      const fallbackSeed = seed || DREAM_PROJECT_SEEDS[Math.floor(Math.random() * DREAM_PROJECT_SEEDS.length)];
      const projectTitle = fallbackSeed.projects[Math.floor(Math.random() * fallbackSeed.projects.length)];
      setProject({
        title: projectTitle,
        tagline: `AI-powered solution for ${fallbackSeed.industry} in ${fallbackSeed.district}`,
        problem: `The ${fallbackSeed.industry.toLowerCase()} sector in ${fallbackSeed.district} faces challenges with manual processes and quality control. Local workers spend hours on tasks that could be automated.`,
        solution: `Build an AI tool that uses ${interest.includes('image') || interest.includes('vision') ? 'computer vision' : 'data analysis'} to solve this problem. The system will work on low-cost Android phones.`,
        techStack: ['Python', 'TensorFlow Lite', 'Flask API', 'Android (React Native)'],
        steps: [
          'Collect 200+ local sample images/data points',
          'Train a classification model using Google Colab',
          'Build a simple API to serve predictions',
          'Create a mobile-friendly UI that works offline',
        ],
        timeline: '4-6 weeks',
        industry: fallbackSeed.industry,
        district: fallbackSeed.district,
        impact: `Helps local ${fallbackSeed.industry.toLowerCase()} workers in ${fallbackSeed.district} save time and improve quality.`,
      });
      setPhase('result');
    }
  };

  const handleCopy = () => {
    if (!project) return;
    const text = `🚀 Dream Project: ${project.title}\n${project.tagline}\n\n📌 Problem: ${project.problem}\n💡 Solution: ${project.solution}\n\n🛠️ Tech: ${project.techStack.join(', ')}\n📍 District: ${project.district}\n⏱️ Timeline: ${project.timeline}\n🎯 Impact: ${project.impact}\n\nGenerated by HUNTER AI for ${studentName}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const reset = () => {
    setPhase('input');
    setProject(null);
    setInterest('');
  };

  // ─── INPUT ───
  if (phase === 'input') {
    return (
      <div className="animate-fade-in-up space-y-4">
        <div className="text-center mb-2">
          <div className="text-4xl mb-2 animate-float">🚀</div>
          <h2 className="text-lg font-bold">Dream Project Generator</h2>
          <p className="text-xs text-hunter-text-muted">Tell Hunter what you care about — get a real AI project brief</p>
        </div>

        <div className="glass-card p-4">
          <label className="text-sm text-hunter-text-muted mb-2 block">
            What industry or problem interests you?
          </label>
          <textarea
            value={interest}
            onChange={e => setInterest(e.target.value)}
            className="hunter-textarea mb-3"
            placeholder='Try: "I care about the textile industry" or "I want to help farmers" or "healthcare in my village"'
            rows={3}
          />

          {/* Quick Tags */}
          <div className="flex gap-1.5 flex-wrap mb-3">
            {['textile', 'agriculture', 'healthcare', 'temple tourism', 'automobile', 'fishing', 'energy'].map(tag => (
              <button key={tag} onClick={() => setInterest(`I care about the ${tag} industry`)}
                className="dream-tag">{tag}</button>
            ))}
          </div>

          <button onClick={generate} disabled={!interest.trim()}
            className="hunter-btn hunter-btn-primary flex items-center justify-center gap-2">
            <Sparkles size={16} /> Generate My Project
          </button>
        </div>
      </div>
    );
  }

  // ─── GENERATING ───
  if (phase === 'generating') {
    return (
      <div className="text-center py-12 animate-fade-in">
        <div className="animate-breathe mb-4">
          <Rocket size={48} className="mx-auto text-hunter-accent-light" />
        </div>
        <p className="text-sm text-hunter-text-muted mb-1">Hunter is crafting your dream project...</p>
        <p className="text-xs text-hunter-text-muted">Matching your interest to Tamil Nadu industries</p>
      </div>
    );
  }

  // ─── RESULT ───
  return (
    <div className="animate-fade-in-up space-y-3">
      <div className="dream-project-card p-5">
        <div className="absolute inset-0 animate-holographic rounded-[18px]" />
        <div className="relative z-10">
          {/* Title */}
          <div className="mb-3">
            <div className="flex items-center gap-2 mb-1">
              <Rocket size={18} style={{ color: '#f59e0b' }} />
              <span className="text-xs font-medium text-hunter-accent-light bg-hunter-accent/10 px-2 py-0.5 rounded-full">
                {project.industry}
              </span>
              <span className="text-xs text-hunter-text-muted">📍 {project.district}</span>
            </div>
            <h2 className="text-lg font-bold">{project.title}</h2>
            <p className="text-sm text-hunter-text-muted italic">{project.tagline}</p>
          </div>

          {/* Problem */}
          <div className="glass-card p-3 mb-2">
            <p className="text-xs font-bold text-red-400 mb-1">📌 Problem</p>
            <p className="text-sm text-hunter-text-muted">{project.problem}</p>
          </div>

          {/* Solution */}
          <div className="glass-card p-3 mb-2">
            <p className="text-xs font-bold text-green-400 mb-1">💡 Solution</p>
            <p className="text-sm text-hunter-text-muted">{project.solution}</p>
          </div>

          {/* Tech Stack */}
          <div className="mb-2">
            <p className="text-xs text-hunter-text-muted mb-1">🛠️ Tech Stack</p>
            <div className="flex gap-1.5 flex-wrap">
              {project.techStack.map((t, i) => (
                <span key={i} className="dream-tech-tag">{t}</span>
              ))}
            </div>
          </div>

          {/* Steps */}
          <div className="glass-card p-3 mb-2">
            <p className="text-xs font-bold text-hunter-accent-light mb-2">📋 Build Steps</p>
            {project.steps.map((step, i) => (
              <div key={i} className="flex items-start gap-2 mb-1.5">
                <span className="dream-step-num">{i + 1}</span>
                <p className="text-xs text-hunter-text-muted">{step}</p>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-1 text-xs text-hunter-text-muted">
              <Clock size={12} /> {project.timeline}
            </div>
            <p className="text-xs text-hunter-text-muted">🎯 {project.impact}</p>
          </div>

          {/* Actions */}
          <div className="flex gap-2">
            <button onClick={handleCopy} className="hunter-btn hunter-btn-primary flex-1 flex items-center justify-center gap-2 text-sm">
              <Copy size={14} /> {copied ? 'Copied!' : 'Share Brief'}
            </button>
            <button onClick={reset} className="hunter-btn hunter-btn-secondary flex-none px-4 text-sm">
              <RefreshCw size={14} />
            </button>
          </div>
        </div>
      </div>
      {copied && <div className="copy-toast">Project brief copied!</div>}
    </div>
  );
}
