import { useMemo } from 'react';
import { Activity, Download } from 'lucide-react';

const EMOTION_COLORS = {
  CONFIDENT: { color: '#22c55e', width: 40, label: 'Calm' },
  CONFUSED: { color: '#f59e0b', width: 25, label: 'Confused' },
  STRESSED: { color: '#ef4444', width: 12, label: 'Stressed' },
  BORED: { color: '#6366f1', width: 8, label: 'Bored' },
};

function buildRiverPath(emotionHistory, width, height) {
  if (!emotionHistory || emotionHistory.length === 0) return { path: '', segments: [] };

  const padding = 20;
  const usableW = width - padding * 2;
  const centerY = height / 2;
  const segmentW = emotionHistory.length > 1 ? usableW / (emotionHistory.length - 1) : usableW;
  const segments = [];

  let pathD = '';

  emotionHistory.forEach((entry, i) => {
    const x = padding + i * segmentW;
    const cfg = EMOTION_COLORS[entry.emotion] || EMOTION_COLORS.CONFIDENT;
    const halfW = cfg.width / 2;

    segments.push({ x, emotion: entry.emotion, color: cfg.color, halfW, topicLabel: entry.topic });

    if (i === 0) {
      pathD += `M ${x} ${centerY - halfW} `;
    } else {
      const prevX = padding + (i - 1) * segmentW;
      const cpX = (prevX + x) / 2;
      const prevCfg = EMOTION_COLORS[emotionHistory[i - 1].emotion] || EMOTION_COLORS.CONFIDENT;
      pathD += `C ${cpX} ${centerY - prevCfg.width / 2}, ${cpX} ${centerY - halfW}, ${x} ${centerY - halfW} `;
    }
  });

  // Draw bottom edge in reverse
  for (let i = emotionHistory.length - 1; i >= 0; i--) {
    const x = padding + i * segmentW;
    const cfg = EMOTION_COLORS[emotionHistory[i].emotion] || EMOTION_COLORS.CONFIDENT;
    const halfW = cfg.width / 2;

    if (i === emotionHistory.length - 1) {
      pathD += `L ${x} ${centerY + halfW} `;
    } else {
      const nextX = padding + (i + 1) * segmentW;
      const cpX = (nextX + x) / 2;
      const nextCfg = EMOTION_COLORS[emotionHistory[i + 1].emotion] || EMOTION_COLORS.CONFIDENT;
      pathD += `C ${cpX} ${centerY + nextCfg.width / 2}, ${cpX} ${centerY + halfW}, ${x} ${centerY + halfW} `;
    }
  }
  pathD += 'Z';

  return { path: pathD, segments };
}

export default function EQLiveDashboard({ emotionHistory, sessionTime }) {
  const svgWidth = 340;
  const svgHeight = 160;

  const { path, segments } = useMemo(
    () => buildRiverPath(emotionHistory, svgWidth, svgHeight),
    [emotionHistory]
  );

  // Stats
  const stats = useMemo(() => {
    if (!emotionHistory || emotionHistory.length === 0) {
      return { confidence: 0, stressPeaks: 0, totalTime: '0m' };
    }
    const conf = emotionHistory.filter(e => e.emotion === 'CONFIDENT').length;
    const stress = emotionHistory.filter(e => e.emotion === 'STRESSED').length;
    const pct = Math.round((conf / emotionHistory.length) * 100);
    const mins = sessionTime ? Math.round(sessionTime / 60) : 0;
    return { confidence: pct, stressPeaks: stress, totalTime: `${mins}m` };
  }, [emotionHistory, sessionTime]);

  const handleExport = async () => {
    const text = `HUNTER EQ Report\n${'='.repeat(30)}\n\nStudent Session Summary\nConfidence: ${stats.confidence}%\nStress Peaks: ${stats.stressPeaks}\nSession Time: ${stats.totalTime}\n\nEmotion Flow:\n${emotionHistory.map((e, i) => `  ${i + 1}. ${e.topic || 'Topic ' + (i + 1)}: ${e.emotion}`).join('\n')}\n\nGenerated by HUNTER AI Tutor`;

    if (navigator.share) {
      try { await navigator.share({ title: 'HUNTER EQ Report', text }); } catch {}
    } else {
      await navigator.clipboard.writeText(text);
    }
  };

  if (!emotionHistory || emotionHistory.length === 0) {
    return (
      <div className="eq-river-container text-center py-8">
        <Activity size={32} className="mx-auto mb-3 text-hunter-text-muted opacity-40" />
        <p className="text-sm text-hunter-text-muted">Complete topics to see your emotion flow</p>
      </div>
    );
  }

  return (
    <div className="animate-fade-in-up space-y-3">
      {/* River Chart */}
      <div className="eq-river-container">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Activity size={16} className="text-hunter-accent-light" />
            <span className="text-sm font-bold">Emotion River</span>
          </div>
          <button onClick={handleExport} className="flex items-center gap-1 text-xs text-hunter-accent-light">
            <Download size={12} /> Export
          </button>
        </div>

        <svg width="100%" viewBox={`0 0 ${svgWidth} ${svgHeight}`} className="overflow-visible">
          <defs>
            {emotionHistory.map((entry, i) => (
              <linearGradient key={i} id={`riverGrad${i}`} x1="0" x2="1" y1="0" y2="0">
                <stop offset="0%" stopColor={EMOTION_COLORS[entry.emotion]?.color || '#22c55e'} stopOpacity="0.6" />
                <stop offset="100%" stopColor={EMOTION_COLORS[emotionHistory[Math.min(i + 1, emotionHistory.length - 1)]?.emotion]?.color || '#22c55e'} stopOpacity="0.6" />
              </linearGradient>
            ))}
            <linearGradient id="riverMainGrad" x1="0%" y1="0%" x2="100%" y2="0%">
              {emotionHistory.map((entry, i) => (
                <stop key={i} offset={`${(i / Math.max(1, emotionHistory.length - 1)) * 100}%`}
                  stopColor={EMOTION_COLORS[entry.emotion]?.color || '#22c55e'} stopOpacity="0.5" />
              ))}
            </linearGradient>
          </defs>

          {/* River body */}
          <path d={path} fill="url(#riverMainGrad)" stroke="none" />
          <path d={path} fill="none" stroke="rgba(255,255,255,0.15)" strokeWidth="1" />

          {/* Topic markers */}
          {segments.map((seg, i) => (
            <g key={i}>
              <circle cx={seg.x} cy={svgHeight / 2} r={4} fill={seg.color} opacity="0.8" />
              <text x={seg.x} y={svgHeight - 5} textAnchor="middle"
                fill="rgba(148,163,184,0.6)" fontSize="8" fontFamily="var(--font-sans)">
                T{i + 1}
              </text>
            </g>
          ))}
        </svg>

        {/* Legend */}
        <div className="flex justify-center gap-4 mt-3">
          {Object.entries(EMOTION_COLORS).map(([key, cfg]) => (
            <div key={key} className="flex items-center gap-1">
              <span className="eq-legend-dot" style={{ background: cfg.color }} />
              <span className="text-[10px] text-hunter-text-muted">{cfg.label}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-2">
        <div className="eq-stat-card">
          <p className="eq-stat-value" style={{ color: '#22c55e' }}>{stats.confidence}%</p>
          <p className="eq-stat-label">Confidence</p>
        </div>
        <div className="eq-stat-card">
          <p className="eq-stat-value" style={{ color: '#ef4444' }}>{stats.stressPeaks}</p>
          <p className="eq-stat-label">Stress Peaks</p>
        </div>
        <div className="eq-stat-card">
          <p className="eq-stat-value" style={{ color: '#a78bfa' }}>{stats.totalTime}</p>
          <p className="eq-stat-label">Duration</p>
        </div>
      </div>
    </div>
  );
}
